package main

import (
	"encoding/json"
	"io/ioutil"
	"log"
	"os"
	"time"
)

type Food struct {
	ID    string //represented as a date string generated by time.Now().Format()
	Name  string
	Label map[string]bool
}

func NewFood(food Food) *Food {
	f := food
	f.ID = time.Now().Format("Mon-Jan-2-15:04:05-2006")
	return &f
}

func (f Food) Equals(comp Food) bool {
	return f.ID == comp.ID
}

func (f Food) HasLabel(label string) bool {
	_, ok := f.Label[label]
	return ok
}

func CheckFileExist(file string) (*bool, error) {
	var b bool
	if _, err := os.Stat(file); err == nil {
		b = true
		return &b, nil
	} else if os.IsNotExist(err) {
		b = false
		return &b, nil
	} else {
		return nil, err
	}
}

//add data to foods.json
func AddFoodToList(data Food) error {
	if b, err := CheckFileExist("resources/foods.json"); err != nil {
		log.Println("File resources/foods.json may or may not exist: " + err.Error())
	} else if !*b {
		os.Create("resources/foods.json")
		ioutil.WriteFile("resources/foods.json", []byte("[]"), 0644)
	}
	file, err := ioutil.ReadFile("resources/foods.json")
	if err != nil {
		return err
	}
	var Foods []Food
	err = json.Unmarshal(file, &Foods)
	if err != nil {
		return err
	}
	Foods = append(Foods, data)
	newFile, err := json.MarshalIndent(Foods, "", "\t")
	if err != nil {
		return err
	}
	err = ioutil.WriteFile("resources/foods.json", newFile, 0644)
	if err != nil {
		return err
	}
	return nil
}

func ChangeFoodInList(data Food) error {
	file, err := ioutil.ReadFile("resources/foods.json")
	if err != nil {
		return err
	}
	var Foods []Food
	err = json.Unmarshal(file, &Foods)
	if err != nil {
		return err
	}
	for i, v := range Foods {
		if v.ID == data.ID {
			Foods[i] = data
			break
		}
	}
	newFile, err := json.MarshalIndent(Foods, "", "\t")
	if err != nil {
		return err
	}
	err = ioutil.WriteFile("resources/foods.json", newFile, 0644)
	if err != nil {
		return err
	}
	return nil
}

//remove data from foods.json
func DeleteFoodFromList(data Food) error {
	file, err := ioutil.ReadFile("resources/foods.json")
	if err != nil {
		return err
	}
	var Foods []Food
	err = json.Unmarshal(file, &Foods)
	if err != nil {
		return err
	}
	var updatedFoods []Food = make([]Food, 0, cap(Foods))
	for _, v := range Foods {
		if !v.Equals(data) {
			updatedFoods = append(updatedFoods, v)
		}
	}
	newFile, err := json.MarshalIndent(updatedFoods, "", "\t")
	if err != nil {
		return err
	}
	err = ioutil.WriteFile("resources/foods.json", newFile, 0644)
	if err != nil {
		return err
	}
	return nil
}

func GetWholeFoodList() ([]Food, error) {
	if b, err := CheckFileExist("resources/foods.json"); err != nil {
		log.Println("File resources/foods.json may or may not exist: " + err.Error())
	} else if !*b {
		os.Create("resources/foods.json")
		ioutil.WriteFile("resources/foods.json", []byte("[]"), 0644)
	}
	file, err := ioutil.ReadFile("resources/foods.json")
	if err != nil {
		return nil, err
	}
	var Foods []Food
	err = json.Unmarshal(file, &Foods)
	if err != nil {
		return nil, err
	}
	return Foods, nil
}
